[WIP ]Assay improvements - issues #369, #370
ISA-tools/isa-api pull request #373
Opened 2020-11-12 17:00 UTC by Zigur

Work in progress, for now, issue #369 is completed, #370 still todo.

2020-11-18 20:47 UTC, Zigur commented
This is now ready to be reviewed and merged. @proccaserra have a look at the outputted ISA tables using https://github.com/Zigur/isa-create-notebook/blob/dev/notebooks/Investigation-from-datascriptor-config.ipynb for instance. Check that there are no duplicates in the node names (I'll add some tests on that too, before merging).

2020-11-19 08:42 UTC, proccaserra requested changes
Line1056 in create/model.py causes an exception "TypeError: expected string or bytes-like object" when the assay definition used is annotated with ontology terms (to reproduce switch flag for MS (annotated) to true, when testing with the notebook).

then at line 2334 in the same module, some required keys are missing "'FreeInductionDecayDataFile" (and possibly "ImageDataFile") - 
TODO: review assay definitions and test all current layouts)

2020-11-19 08:42 UTC, proccaserra commented on isatools/create/model.py
> +                    assert isa_class in {RawDataFile, RawSpectralDataFile}
at least add the following key "'FreeInductionDecayDataFile"  (and possibly "ImageDataFile") 
TODO: review assay definitions and test all current layouts)

2020-11-20 17:03 UTC, Zigur commented on isatools/create/model.py
> +                    assert isa_class in {RawDataFile, RawSpectralDataFile}
This should be fixed now

2020-11-24 12:35 UTC, Zigur commented
This is mostly completed, I'd say. I have included support for all data file types, both raw and derived, for completeness:

https://github.com/ISA-tools/isa-api/blob/746fde3f67aafc0f0a9cc0e3014ea4854c035baf/isatools/create/model.py#L2349-L2355

I have added two prefixes to the node names to clarify the notations:
- `AT` is prepended to the assay type id
- `S` is prepended to the start node (or sample node) index
- `R` is prepended to the replicate node index

Some examples:
- extract name: `AT1-S9-Extract-R1`
- labelled extract name: `AT1-S9-LE-R1`
- process name:  `AT1-S9-mass-spectrometry-Acquisition-R1`
- raw data file name:  `AT1-S9-raw-spectral-data-file-R1`

@proccaserra have a look at [this notebook](https://github.com/Zigur/isa-create-notebook/blob/dev/notebooks/Investigation-from-datascriptor-config-observational-variables-and-ontology-annotation.ipynb) for reviewing a scenario with the ontology annotated MS assay and the NMR assay

2020-12-14 18:33 UTC, Zigur commented
This seems to work also for assays with chained protocols now (see [this](https://github.com/Zigur/isa-create-notebook/blob/dev/notebooks/Investigation-from-datascriptor-config.ipynb) notebook, at the moment the only functional one, others to be updated soon).

2020-12-15 15:34 UTC, proccaserra commented
looks good to me now.

2020-12-15 16:50 UTC, merged