Issue 511
ISA-tools/isa-api pull request #514
Opened 2023-11-13 15:17 UTC by proccaserra

fixes issue 511 and issue 512.

2023-11-20 11:51 UTC, terazus requested changes
Minor changes.

2023-11-20 11:51 UTC, terazus commented on isatools/model/assay.py
> +
```suggestion
self.__comments = comments or []   # or self.__comments = comments if comments else []
```

2023-11-20 11:51 UTC, terazus commented on isatools/model/utils.py
> +def compute_checksum(path, isa_file_object: DataFile, checksum_type):
Missing docstring

2023-11-20 11:51 UTC, terazus commented on isatools/model/utils.py
> +def update_hash(path, file, hash_func):
Missing docstring

2023-11-20 11:51 UTC, terazus commented on tests/convert/test_isatab2json.py
> +            self.assertEqual(isajson_read.studies[0].assays[0].comments[0].value, "ena")
```suggestion          
              self.assertEqual(isajson_read.studies[0].assays[0].comments[0].value(ISA.studies[0].assays[0].comments[0].value)
```

2023-11-20 11:51 UTC, terazus commented on tests/isajson/test_isajson.py
> +    def test_json_load_and_dump_bii_s_test(self):
There are missing assertions in this test

2023-11-20 11:51 UTC, terazus commented on tests/isatab/test_isatab.py
> +sample1\textraction\textract1\tnucleic acid sequencing\tassay-1\tdatafile.raw\tmd5\t123134214"""
Make \t123134214 a proper variable that you can pass to the `Comment()` et line 1387.

2024-02-12 10:07 UTC, terazus commented on isatools/convert/json2isatab.py
> +        # -*- coding: utf-8 -*
Why add a tab here ?

2024-02-12 10:32 UTC, terazus commented on isatools/isatab/dump/write.py
> +                    #                 output.comments))
No comments in production

2024-02-12 10:41 UTC, terazus commented on isatools/isatab/dump/write.py
> +                        map(lambda x: get_characteristic_columns(olabel, x) ,
no white space before comma

2024-02-12 10:42 UTC, terazus commented on isatools/isatab/dump/write.py
> +                        # print(columns)
No comment in production

2024-02-12 10:42 UTC, terazus commented on isatools/isatab/dump/write.py
> -                        columns.append(output.label)
Why remove this ?

2024-02-12 10:50 UTC, terazus commented on isatools/isatab/dump/write.py
> +                        #     # else:
No comments in production

2024-02-12 10:52 UTC, terazus commented on isatools/isatab/dump/write.py
> +
Don't repeat yourself

2024-02-12 11:09 UTC, terazus commented on isatools/isatab/dump/write.py
> +                                    df_dict[colabel][-1] = co.value
Remove extra tabs

2024-02-12 11:27 UTC, terazus commented on isatools/isatab/load/ProcessSequenceFactory.py
> +                        process = Process(executes_protocol=protocol_ref, name="TOTO-{}-".format(_) + protocol_ref)
Remove name parameter

2024-02-13 11:09 UTC, terazus commented on isatools/isatab/dump/write.py
>                          pass  # handled in process
If i remember correctly, you said this piece was handled somewhere else in the code?

2024-02-21 19:25 UTC, proccaserra commented on isatools/isatab/dump/write.py
>                          pass  # handled in process
it seems that are 2 passes: 1 to build the header, 1 to population the rows
@line 315 (latest commit) and @line 378 respectively. So this bit seems to do ...not much

2024-02-21 19:39 UTC, proccaserra commented on tests/utils/test_isatools_utils.py
> +        self.assertIn("/api/ontologies/efo?lang=en", ontology_source.file)
+1, no time to write the test with a mock

2024-02-22 10:46 UTC, terazus requested changes

2024-02-22 10:46 UTC, terazus commented on tests/test_clients/test_mw2isa.py
> +        # self.assertEqual("conversion failed, validation was not invoked")
remove

2024-02-22 10:46 UTC, terazus commented on tests/test_sra.py
> +            os.path.join(utils.TAB_DATA_DIR, 'BII-S-7'), ['1EU.sff', '2BF.sff'])
why ?

2024-02-22 10:46 UTC, terazus commented on tests/test_tests_utils.py
What going on in this file ?

2024-02-23 09:19 UTC, proccaserra commented on tests/isatab/test_isatab.py
> +            self.assertEqual(len(assay_microarray.process_sequence), 46)  # 46 processes in in a_microarray.txt
yes, investigating

2024-02-23 09:30 UTC, proccaserra commented on tests/test_sra.py
> +            os.path.join(utils.TAB_DATA_DIR, 'BII-S-7'), ['1EU.sff', '2BF.sff'])
wanted to be sure the array was properly handled, now removed

2024-02-23 14:18 UTC, proccaserra commented on tests/model/test_utils.py
> +from isatools.tests import utils
no longer needed

2024-02-23 15:00 UTC, proccaserra commented on isatools/net/ols.py
> +OLS_API_BASE_URI = "https://www.ebi.ac.uk/ols4/api"
not systematically, it supports our use of it so far.

2024-02-23 15:23 UTC, proccaserra commented on tests/create/test_create_connectors.py
> -
because it is already tested in the constructor of OntologyAnnotation object when passing a string instead of an OntologySource object

2024-02-23 15:34 UTC, proccaserra commented on isatools/create/assay_templates.py
> +        ontology_annotation = OntologyAnnotation(term=term_name, term_accession="", term_source=onto_src)
Yes this could benefit from a refactoring:
- [ ] allow another argument to pass an ontology source object
- [ ] raise Error if not
- [ ] associated tests

2024-02-23 15:35 UTC, proccaserra commented on tests/isatab/test_isatab.py
> +            self.assertEqual(len(assay_microarray.process_sequence), 46)  # 46 processes in in a_microarray.txt
now fixed. has to do _NODES_ASSAY_LABEL in constants.py 
TODO: rewrite more meaning tests.

2024-02-23 15:39 UTC, proccaserra commented on tests/isatab/test_isatab.py
> +            self.assertEqual(len(assay_microarray.process_sequence), 46)  # 46 processes in in a_microarray.txt
see https://github.com/ISA-tools/isa-api/issues/541

2024-02-23 16:54 UTC, proccaserra commented on isatools/isatab/load/ProcessSequenceFactory.py
> +    # _LABELS_DATA_NODES,
commented code removed

2024-02-23 16:54 UTC, proccaserra commented on isatools/isatab/load/ProcessSequenceFactory.py
> +    # _LABELS_ASSAY_NODES,
ditto

2024-02-23 17:17 UTC, proccaserra commented on isatools/model/material.py
> +
now in issue-543

2024-02-23 17:19 UTC, proccaserra commented on isatools/isatab/utils.py
> -    _LABELS_DATA_NODES,
felt it these values should not change so made sense to have them in that class rather than utils

2024-02-23 17:21 UTC, proccaserra commented on isatools/sra.py
> +        this_sample = None
there was a shadowing warning from the linter

2024-02-23 17:22 UTC, proccaserra commented on isatools/sra.py
> +                            if file_ext in '.gz':
swapped around it seems

2024-02-23 17:23 UTC, proccaserra commented on tests/convert/test_json2sra.py
> +import json.decoder
fixed

2024-02-23 17:24 UTC, proccaserra commented on tests/convert/test_json2sra.py
> +    #
gone

2024-02-23 17:30 UTC, proccaserra commented on tests/create/test_assay_templates.py
> +        self.assertEqual(str(stuff), str((isatools.model.OntologyAnnotation(term='something', term_source=isatools.model.OntologySource(name='onto', file='', version='', description='', comments=[]),
fixed

2024-02-23 17:31 UTC, proccaserra commented on tests/isajson/test_isajson.py
> +        self.assertEqual(assays['materials']['otherMaterials'][1  ]["type"], "Extract Name")
fixed

2024-02-26 14:53 UTC, terazus requested changes

2024-02-26 14:53 UTC, terazus commented on isatools/model/utils.py
> +    return isa_file_object
Didn't we say this should be in the notebook if it's not used by the model ?

2024-02-26 14:53 UTC, terazus commented on isatools/net/mw2isa/__init__.py
> +    a method to metabolomics workbench tabular file as list of lists
```suggestion
    """A method to metabolomics workbench tabular file as list of lists
```

2024-02-26 14:53 UTC, terazus commented on isatools/net/mw2isa/__init__.py
> +    a method to write an ISA study file
```suggestion
    """A method to write an ISA study file
```

2024-02-26 14:53 UTC, terazus commented on isatools/net/mw2isa/__init__.py
> +    METHOD: given a Metabolomics Workbench Identifier, downloads the
```suggestion
    """Given a Metabolomics Workbench Identifier, downloads the
```

2024-02-26 14:53 UTC, terazus commented on isatools/net/mw2isa/__init__.py
> +    Main method to invoke metabolomics workbench conversion to isa format
```suggestion
    """Main method to invoke metabolomics workbench conversion to isa format
```

2024-03-25 10:57 UTC, proccaserra commented on tests/isajson/test_isajson.py
> +            assay_gx = [a for a in study_bii_s_test['assays'] if a['filename'] == 'a_assay.txt'][0]
it seems to be testing json.loads/json.dumps once the ISA objects have been created

2024-03-25 11:02 UTC, proccaserra commented on tests/isajson/test_isajson.py
> +            self.assertEqual(assay_gx['materials']['otherMaterials'][3]["type"], "Labeled Extract Name")
it seems because the tests are written to work on the json, not the object

2024-03-25 11:10 UTC, proccaserra commented on tests/isajson/test_isajson.py
> +                                                                              term_accession="http://purl.obolibrary.org/obo/UO_0000009")))
now fixed, test renamed and simplified

2024-03-25 11:12 UTC, proccaserra commented on tests/isajson/test_isajson.py
> +        self.assertIsInstance(isa_j, str)
agree with the recommendation.

2024-03-25 11:13 UTC, proccaserra commented on tests/isatab/test_isatab.py
> +    def test_isatab_dump_source_sample_char_quant(self):
true but no time to refactor now

2024-03-25 14:20 UTC, proccaserra commented on isatools/net/mw2isa/__init__.py
> +    except IOError:
as discussed, to use a less generic exception but review needed to check if this error type is the most suited

2024-03-25 14:36 UTC, proccaserra commented on tests/model/test_ontology_annotation.py
> +        self.assertFalse(self.ontology_annotation.term_source == 'test_term_source')
fixed with AssertEqual AssertIsIstance

2024-07-15 08:07 UTC, knirirr approved these changes

2024-07-15 08:27 UTC, merged